### ISSUE TITLE
Odd solid-colored regions when dithering

### ISSUE THREAD

**Issue by LucasTizma** [pornel/pngquant#147]
Sometimes when dithering is selected, there will be some oddly-colored solid areas that look strange (near the character's right eye):

![dithered](https://cloud.githubusercontent.com/assets/66559/6814600/53e017c8-d23d-11e4-8f53-c8eec078898e.png)

If dithering is disabled, it looks fine around the same area:

![no-dither](https://cloud.githubusercontent.com/assets/66559/6814605/6b3ef2fe-d23d-11e4-93d6-cf077e7018c1.png)

If I dither AND enable the IE-specific fix, it doesn't produce that weird color patch:

![ie-alpha](https://cloud.githubusercontent.com/assets/66559/6814623/8199dc76-d23d-11e4-8063-153b8d86ecbf.png)

Here is the original image:

![original](https://cloud.githubusercontent.com/assets/66559/6814629/884f1cb6-d23d-11e4-961d-dc0ef91fe657.png)

**Note that even though I used ImageAlpha in these screenshots, I verified that this same dithering behavior exists for every version of pngquant I tried, including the master branch.**

What is interesting is that the appearance of these artifacts seems somewhat random. I have several animated frames of this character, and these dithering artifacts only appear on some frames, though it is always in the same area. Out of 170+ frames of this character moving around, maybe 10% of them exhibit noticeable artifacts, always in that same area. What is particularly odd about the gradient pattern near that portion of his face?

Here is a link to a sample frame that will produce this dithering oddity near his right eye using the latest version of pngquant: http://cld.tiz.ma/image/2k173t2u032x/01_NORMAL_011.png

Is this possibly related to some of the other dithering issues that I've seen discussions about here?

**Comment by pornel** [comment]
I suspect this is a problem in the way dithering handles overflow. Error diffusion sometimes creates values out of range, and when they're clamped the shade of color changes.

**Comment by LucasTizma** [comment]
What seems interesting is that the surrounding frames of the same character don't show these errors even though the actual image might be nearly identical:

No error:
![1](https://cloud.githubusercontent.com/assets/66559/6834142/2b0e0dfc-d2ef-11e4-9453-5c84c947b6d2.png)

Error, just one frame after:
![2](https://cloud.githubusercontent.com/assets/66559/6834147/34cc21ee-d2ef-11e4-9674-d87717784993.png)

That being said, is there anything to be done about this? Or should I just be careful to tweak individual frames that are erroneous by, say, applying a slight noise to the source image and hope that pngquant's processing on that doesn't produce these artifacts?

**Comment by pornel** [comment]
Try `--floyd=0.5`

**Comment by LucasTizma** [comment]
Ah I didn't realize this was an option! Yeah, `--floyd=0.5` did the trick! Does this basically indicate how much dithering occurs?

**Comment by pornel** [comment]
Yes.

**Comment by pornel** [comment]
Good news! I've found the cause, and it's due to cleverness in the fast palette search algorithm (actually not related to dithering).

Bad news it's complicated to fix :)

**Comment by pornel** [comment]
This is fixed in ad61aa1b54ea04d660d9a924234fee7f4c16f6ec

**Comment by LucasTizma** [comment]
Awesome. Thanks for fixing this. :)

**Comment by LucasTizma** [comment]
Hm. I'm still seeing this issue crop up on master. :( In particular, here is an image that always produces the odd color region: http://cld.tiz.ma/image/1z2S2I2S0d02/01_NORMAL_011.png

This is the command I'm using:

`./pngquant --force --speed 1 256 ~/Desktop/01_NORMAL/*.png`

With `--floyd=0.5`, it's less noticeable, but some frames still exhibit the issue.

**Comment by pornel** [comment]
With version compiled from 1af5327862b7158bbae70571506c74bc44ba2739 I'm getting:

![01_normal_011-fs8](https://cloud.githubusercontent.com/assets/72159/7089045/dbf10f22-df90-11e4-982b-3c92ad8ae7da.png)

It looks OK to me?

**Comment by LucasTizma** [comment]
Interesting. It was the `--speed 1` option that was still resulting in the screwed up colors. The default works just fine. Isn't 1 supposed to be the "best"?
